[versions]
kotlin = "1.9.0"
kotlin-coroutines = "1.7.3"
junit-jupiter = "5.9.3"

[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
