#resolver:
  #  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/3.yaml

resolver: lts-21.3

packages:
  - .

extra-deps:
  - gi-gtk-3.0.41
  - megaparsec-9.4.1
  - void-0.7.3
  - gi-pango-1.0.29

allow-newer: true